language: node_js

node_js:
  - '12'

jobs:
  include:
    - stage: lint
      script:
        - commitlint-travis
    - stage: release
      if: branch = master
      script: true
      node_js: 12
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
