export const dependencies = {
  prod: ['chalk', 'hapi', 'confidence'],
  dev: [
    '@babel/core',
    '@commitlint/cli',
    '@commitlint/config-conventional',
    '@dixeed/eslint-config',
    'babel-cli',
    'babel-core',
    'babel-eslint',
    'babel-jest',
    'babel-plugin-module-resolver',
    'babel-plugin-transform-class-properties',
    'babel-preset-env',
    'commitizen',
    'cz-conventional-changelog',
    'eslint',
    'eslint-plugin-jest',
    'husky',
    'jest',
    'last-release-git',
    'lint-staged',
    'nodemon',
    'prettier',
    'semantic-release',
    'travis-deploy-once',
  ],
};
